export function AddMateriaTools() {
    console.log("materia-dnd | Tools: Setting up tools.");
    CONFIG.DND5E.toolIds.alchemist = 'Compendium.materia-dnd.items.Item.83LAuq9DnKxUPkK3';
    CONFIG.DND5E.toolIds.bagpipes = 'Compendium.materia-dnd.items.Item.YUrF3KWUTFCpcipz';
    CONFIG.DND5E.toolIds.brewer = 'Compendium.materia-dnd.items.Item.wOLZsUUdyC3irxrH';
    CONFIG.DND5E.toolIds.calligrapher = 'Compendium.materia-dnd.items.Item.SE06ha7PRDzkcs7z';
    CONFIG.DND5E.toolIds.carpenter = 'Compendium.materia-dnd.items.Item.0sDdZhWRTNDtBaC0';
    CONFIG.DND5E.toolIds.cartographer = 'Compendium.materia-dnd.items.Item.Fi57ZtO6lrpVEnSF';
    CONFIG.DND5E.toolIds.chess = 'Compendium.materia-dnd.items.Item.ygsYJ0cmnDaFMi9x';
    CONFIG.DND5E.toolIds.cobbler = 'Compendium.materia-dnd.items.Item.XMkB6R1IxNqOKclX';
    CONFIG.DND5E.toolIds.cook = 'Compendium.materia-dnd.items.Item.HAXbI4L9BZi9daeg';
    CONFIG.DND5E.toolIds.dice = 'Compendium.materia-dnd.items.Item.w3qSOIETlbfTYpeo';
    CONFIG.DND5E.toolIds.disg = 'Compendium.materia-dnd.items.Item.N10XQUYHxH9AQtuo';
    CONFIG.DND5E.toolIds.drum = 'Compendium.materia-dnd.items.Item.NHX1CDLnhZEaD23j';
    CONFIG.DND5E.toolIds.dulcimer = 'Compendium.materia-dnd.items.Item.HIO0Ryqg6EHxUw8H';
    CONFIG.DND5E.toolIds.flute = 'Compendium.materia-dnd.items.Item.xTp8k7cyQwVFUeBM';
    CONFIG.DND5E.toolIds.forgery = 'Compendium.materia-dnd.items.Item.ng80KvzjGDSwNHSW';
    CONFIG.DND5E.toolIds.glassblower = 'Compendium.materia-dnd.items.Item.HVEQ6VwtnldPxihB';
    CONFIG.DND5E.toolIds.herb = 'Compendium.materia-dnd.items.Item.FPqqnaM81qvelTUT';
    CONFIG.DND5E.toolIds.horn = 'Compendium.materia-dnd.items.Item.VBtjvXEhDEMmPsF7';
    CONFIG.DND5E.toolIds.jeweler = 'Compendium.materia-dnd.items.Item.CYuB2ewjYtRLBRkl';
    CONFIG.DND5E.toolIds.leatherworker = 'Compendium.materia-dnd.items.Item.';
    CONFIG.DND5E.toolIds.lute = 'Compendium.materia-dnd.items.Item.ySZNbYDsHsKHXgFR';
    CONFIG.DND5E.toolIds.lyre = 'Compendium.materia-dnd.items.Item.0ucLE4RemJH6OO01';
    CONFIG.DND5E.toolIds.mason = 'Compendium.materia-dnd.items.Item.4TG48Vev45oXS0QN';
    CONFIG.DND5E.toolIds.navg = 'Compendium.materia-dnd.items.Item.gHCQjIdIqdfw9PKW';
    CONFIG.DND5E.toolIds.painter = 'Compendium.materia-dnd.items.Item.IQJV0rIvfJsfgJCi';
    CONFIG.DND5E.toolIds.panflute = 'Compendium.materia-dnd.items.Item.AuQqlPuaXThdjY1i';
    CONFIG.DND5E.toolIds.pois = 'Compendium.materia-dnd.items.Item.tnSGzoYybcKQq49W';
    CONFIG.DND5E.toolIds.potter = 'Compendium.materia-dnd.items.Item.4MWN1PfJLbEMIot6';
    CONFIG.DND5E.toolIds.shawn = 'Compendium.materia-dnd.items.Item.JABwJToIOtPpeC3e';
    CONFIG.DND5E.toolIds.smith = 'Compendium.materia-dnd.items.Item.pmcRCv9YQ5wuiYZ5';
    CONFIG.DND5E.toolIds.thief = 'Compendium.materia-dnd.items.Item.ehq4ZWJVSI9SGEzm';
    CONFIG.DND5E.toolIds.tinker = 'Compendium.materia-dnd.items.Item.4t9qac2NnnSYNyP7';
    CONFIG.DND5E.toolIds.viol = 'Compendium.materia-dnd.items.Item.cxTYWoEBh4tyyEm8';
    CONFIG.DND5E.toolIds.weaver = 'Compendium.materia-dnd.items.Item.UL5rVwNxwSTpUoW9';
    CONFIG.DND5E.toolIds.woodcarver = 'Compendium.materia-dnd.items.Item.uti4bnSgVQachbEy';
    console.log("materia-dnd | Tools: Added tools.");
    console.log("materia-dnd | Tools: Completed setup.");
}