export function AddMateriaTools() {
    console.log("materia-dnd | Tools: Setting up tools.");
    CONFIG.DND5E.tools.alchemist.id = 'Compendium.materia-dnd.items.Item.83LAuq9DnKxUPkK3';
    CONFIG.DND5E.tools.bagpipes.id = 'Compendium.materia-dnd.items.Item.YUrF3KWUTFCpcipz';
    CONFIG.DND5E.tools.brewer.id = 'Compendium.materia-dnd.items.Item.wOLZsUUdyC3irxrH';
    CONFIG.DND5E.tools.calligrapher.id = 'Compendium.materia-dnd.items.Item.SE06ha7PRDzkcs7z';
    CONFIG.DND5E.tools.card.id = 'Compendium.materia-dnd.items.Item.SCzPV7FXYeJYQIpH';
    CONFIG.DND5E.tools.carpenter.id = 'Compendium.materia-dnd.items.Item.0sDdZhWRTNDtBaC0';
    CONFIG.DND5E.tools.cartographer.id = 'Compendium.materia-dnd.items.Item.Fi57ZtO6lrpVEnSF';
    CONFIG.DND5E.tools.chess.id = 'Compendium.materia-dnd.items.Item.ygsYJ0cmnDaFMi9x';
    CONFIG.DND5E.tools.cobbler.id = 'Compendium.materia-dnd.items.Item.XMkB6R1IxNqOKclX';
    CONFIG.DND5E.tools.cook.id = 'Compendium.materia-dnd.items.Item.HAXbI4L9BZi9daeg';
    CONFIG.DND5E.tools.dice.id = 'Compendium.materia-dnd.items.Item.w3qSOIETlbfTYpeo';
    CONFIG.DND5E.tools.disg.id = 'Compendium.materia-dnd.items.Item.N10XQUYHxH9AQtuo';
    CONFIG.DND5E.tools.drum.id = 'Compendium.materia-dnd.items.Item.NHX1CDLnhZEaD23j';
    CONFIG.DND5E.tools.dulcimer.id = 'Compendium.materia-dnd.items.Item.HIO0Ryqg6EHxUw8H';
    CONFIG.DND5E.tools.flute.id = 'Compendium.materia-dnd.items.Item.xTp8k7cyQwVFUeBM';
    CONFIG.DND5E.tools.forg.id = 'Compendium.materia-dnd.items.Item.ng80KvzjGDSwNHSW';
    CONFIG.DND5E.tools.glassblower.id = 'Compendium.materia-dnd.items.Item.HVEQ6VwtnldPxihB';
    CONFIG.DND5E.tools.herb.id = 'Compendium.materia-dnd.items.Item.FPqqnaM81qvelTUT';
    CONFIG.DND5E.tools.horn.id = 'Compendium.materia-dnd.items.Item.VBtjvXEhDEMmPsF7';
    CONFIG.DND5E.tools.jeweler.id = 'Compendium.materia-dnd.items.Item.CYuB2ewjYtRLBRkl';
    CONFIG.DND5E.tools.leatherworker.id = 'Compendium.materia-dnd.items.Item.';
    CONFIG.DND5E.tools.lute.id = 'Compendium.materia-dnd.items.Item.ySZNbYDsHsKHXgFR';
    CONFIG.DND5E.tools.lyre.id = 'Compendium.materia-dnd.items.Item.0ucLE4RemJH6OO01';
    CONFIG.DND5E.tools.mason.id = 'Compendium.materia-dnd.items.Item.4TG48Vev45oXS0QN';
    CONFIG.DND5E.tools.navg.id = 'Compendium.materia-dnd.items.Item.gHCQjIdIqdfw9PKW';
    CONFIG.DND5E.tools.painter.id = 'Compendium.materia-dnd.items.Item.IQJV0rIvfJsfgJCi';
    CONFIG.DND5E.tools.panflute.id = 'Compendium.materia-dnd.items.Item.AuQqlPuaXThdjY1i';
    CONFIG.DND5E.tools.pois.id = 'Compendium.materia-dnd.items.Item.tnSGzoYybcKQq49W';
    CONFIG.DND5E.tools.potter.id = 'Compendium.materia-dnd.items.Item.4MWN1PfJLbEMIot6';
    CONFIG.DND5E.tools.shawm.id = 'Compendium.materia-dnd.items.Item.JABwJToIOtPpeC3e';
    CONFIG.DND5E.tools.smith.id = 'Compendium.materia-dnd.items.Item.pmcRCv9YQ5wuiYZ5';
    CONFIG.DND5E.tools.thief.id = 'Compendium.materia-dnd.items.Item.ehq4ZWJVSI9SGEzm';
    CONFIG.DND5E.tools.tinker.id = 'Compendium.materia-dnd.items.Item.4t9qac2NnnSYNyP7';
    CONFIG.DND5E.tools.viol.id = 'Compendium.materia-dnd.items.Item.cxTYWoEBh4tyyEm8';
    CONFIG.DND5E.tools.weaver.id = 'Compendium.materia-dnd.items.Item.UL5rVwNxwSTpUoW9';
    CONFIG.DND5E.tools.woodcarver.id = 'Compendium.materia-dnd.items.Item.uti4bnSgVQachbEy';
    console.log("materia-dnd | Tools: Added tools.");
    console.log("materia-dnd | Tools: Completed setup.");
}