export function AddMateriaTools() {
    console.log("materia-dnd | Tools: Setting up tools.");
    CONFIG.DND5E.tools.alchemist.id = 'Compendium.materia-dnd.items.Item.matIteSupplAlche';
    CONFIG.DND5E.tools.bagpipes.id = 'Compendium.materia-dnd.items.Item.matIteBagpipes00';
    CONFIG.DND5E.tools.brewer.id = 'Compendium.materia-dnd.items.Item.matIteSupplBrewe';
    CONFIG.DND5E.tools.calligrapher.id = 'Compendium.materia-dnd.items.Item.matIteSupplCalli';
    CONFIG.DND5E.tools.card.id = 'Compendium.materia-dnd.items.Item.matIteCardSet000';
    CONFIG.DND5E.tools.carpenter.id = 'Compendium.materia-dnd.items.Item.matIteToolCarpen';
    CONFIG.DND5E.tools.cartographer.id = 'Compendium.materia-dnd.items.Item.matIteToolCartog';
    CONFIG.DND5E.tools.chess.id = 'Compendium.materia-dnd.items.Item.matIteChessSet00';
    CONFIG.DND5E.tools.cobbler.id = 'Compendium.materia-dnd.items.Item.matIteToolCobble';
    CONFIG.DND5E.tools.cook.id = 'Compendium.materia-dnd.items.Item.matIteToolCooks0';
    CONFIG.DND5E.tools.dice.id = 'Compendium.materia-dnd.items.Item.matIteDiceSet000';
    CONFIG.DND5E.tools.disg.id = 'Compendium.materia-dnd.items.Item.matIteDisguiseKi';
    CONFIG.DND5E.tools.drum.id = 'Compendium.materia-dnd.items.Item.matIteDrum000000';
    CONFIG.DND5E.tools.dulcimer.id = 'Compendium.materia-dnd.items.Item.matIteDulcimer00';
    CONFIG.DND5E.tools.flute.id = 'Compendium.materia-dnd.items.Item.matIteFlute00000';
    CONFIG.DND5E.tools.forg.id = 'Compendium.materia-dnd.items.Item.matIteForgeryKit';
    CONFIG.DND5E.tools.glassblower.id = 'Compendium.materia-dnd.items.Item.matIteToolGlassb';
    CONFIG.DND5E.tools.herb.id = 'Compendium.materia-dnd.items.Item.matIteHerbalismK';
    CONFIG.DND5E.tools.horn.id = 'Compendium.materia-dnd.items.Item.matIteHorn000000';
    CONFIG.DND5E.tools.jeweler.id = 'Compendium.materia-dnd.items.Item.matIteToolJewele';
    CONFIG.DND5E.tools.leatherworker.id = 'Compendium.materia-dnd.items.Item.matIteToolLeathe';
    CONFIG.DND5E.tools.lute.id = 'Compendium.materia-dnd.items.Item.matIteLute000000';
    CONFIG.DND5E.tools.lyre.id = 'Compendium.materia-dnd.items.Item.matIteLyre000000';
    CONFIG.DND5E.tools.mason.id = 'Compendium.materia-dnd.items.Item.matIteToolMasons';
    CONFIG.DND5E.tools.navg.id = 'Compendium.materia-dnd.items.Item.matIteToolNaviga';
    CONFIG.DND5E.tools.painter.id = 'Compendium.materia-dnd.items.Item.matIteToolPainte';
    CONFIG.DND5E.tools.panflute.id = 'Compendium.materia-dnd.items.Item.matItePanFlute00';
    CONFIG.DND5E.tools.pois.id = 'Compendium.materia-dnd.items.Item.matItePoisonerKi';
    CONFIG.DND5E.tools.potter.id = 'Compendium.materia-dnd.items.Item.matIteToolPotter';
    CONFIG.DND5E.tools.shawm.id = 'Compendium.materia-dnd.items.Item.matIteShawm00000';
    CONFIG.DND5E.tools.smith.id = 'Compendium.materia-dnd.items.Item.matIteToolSmiths';
    CONFIG.DND5E.tools.thief.id = 'Compendium.materia-dnd.items.Item.matIteToolThieve';
    CONFIG.DND5E.tools.tinker.id = 'Compendium.materia-dnd.items.Item.matIteToolTinker';
    CONFIG.DND5E.tools.viol.id = 'Compendium.materia-dnd.items.Item.matIteViol000000';
    CONFIG.DND5E.tools.weaver.id = 'Compendium.materia-dnd.items.Item.matIteToolWeaver';
    CONFIG.DND5E.tools.woodcarver.id = 'Compendium.materia-dnd.items.Item.matIteToolWoodca';
    console.log("materia-dnd | Tools: Added tools.");
    console.log("materia-dnd | Tools: Completed setup.");
}